site_name: NSI - Arbres
theme:
  name: material
  features:
    - navigation.sections
site_url: https://erwandemerville.github.io/nsi_arbres/
nav:
  - Cours:
    - Définitions et vocabulaire: vocabulaire.md
    - Parcours d'arbres binaires: parcours.md
  - Exercices:
    - Exercices - Vocabulaire sur les arbres: exercices_vocabulaire.md
    - Exercices - Parcours d'arbres binaires: fiche2_parcours.pdf

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
  - toc:
      title: Sur cette page
  - admonition
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

