site_name: NSI - Arbres
theme:
  name: material
site_url: https://erwandemerville.github.io/nsi_arbres/
nav:
    - Définitions et vocabulaire: vocabulaire
    - Parcours d'arbres binaires: parcours
    - Fiche d'exercices 1: fiche1_vocabulaire.pdf
    
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

